[
  ../../src/bitte_ci/artificer.cr
  ../../src/bitte_ci/cli.cr
  ../../src/bitte_ci/cli/command.cr
  ../../src/bitte_ci/commander.cr
  ../../src/bitte_ci/libgit2.cr
  ../../src/bitte_ci/loki.cr
  ../../src/bitte_ci/simple_config.cr
  ../../src/bitte_ci/time.cr
  ../../src/bitte_ci/uuid.cr
]
