[
  ../../cue/schema.cue
  ../../src/bitte_ci/cli.cr
  ../../src/bitte_ci/cli/queue.cr
  ../../src/bitte_ci/github_hook.cr
  ../../src/bitte_ci/job_config.cr
  ../../src/bitte_ci/runner.cr
  ../../src/bitte_ci/simple_config.cr
  ../../src/bitte_ci/uuid.cr
]
