[
  ../../src/bitte_ci/cli.cr
  ../../src/bitte_ci/cli/migrate.cr
  ../../src/bitte_ci/github_hook.cr
  ../../src/bitte_ci/line.cr
  ../../src/bitte_ci/migrator.cr
  ../../src/bitte_ci/model.cr
  ../../src/bitte_ci/simple_config.cr
  ../../src/bitte_ci/time.cr
  ../../src/bitte_ci/uuid.cr
]
